import { ICharacter, ICharacterBank, ILesson } from "~/interfaces";
import {
  Lesson_1_1,
  Lesson_1_2,
  Lesson_1_3,
  Lesson_1_4,
  Lesson_1_5,
  Lesson_1_6,
  Lesson_1_7,
  Lesson_1_8,
  Lesson_1_9,
  Lesson_1_10,
  Lesson_1_11,
  Lesson_1_12,
  Lesson_1_13,
  Lesson_1_14,
  Lesson_1_15,
  Lesson_1_16,
  Lesson_1_17,
  Lesson_1_18,
} from "~/lessonComponents/lesson_1";
import {
  Lesson_0_1,
  Lesson_0_2,
  Lesson_0_3,
  Lesson_0_4,
  Lesson_0_5,
  Lesson_0_6,
  Lesson_0_7,
  Lesson_0_8,
  Lesson_0_9,
  Lesson_0_10,
  Lesson_0_11,
  Lesson_0_12,
  Lesson_0_13,
  Lesson_0_14,
  Lesson_0_15,
  Lesson_0_16,
  Lesson_0_17,
  Lesson_0_18,
  Lesson_0_19,
  Lesson_0_20,
  Lesson_0_21,
  Lesson_0_22,
  Lesson_0_23,
  Lesson_0_24,
  Lesson_0_25,
  Lesson_0_26,
  Lesson_0_27,
  Lesson_0_28,
  Lesson_0_29,
  Lesson_0_30,
  Lesson_0_31,
  Lesson_0_32,
  Lesson_0_33,
  Lesson_0_34,
  Lesson_0_35,
  Lesson_0_36,
  Lesson_0_37,
  Lesson_0_38,
  Lesson_0_39,
  Lesson_0_40,
  Lesson_0_41,
  Lesson_0_42,
  Lesson_0_43,
  Lesson_0_44,
  Lesson_0_45,
  Lesson_0_46,
  Lesson_0_47,
  Lesson_0_48,
  Lesson_0_49,
  Lesson_0_50,
} from "~/lessonComponents/lesson_0";

export const LESSON_CHARACTERS: ICharacterBank[] = [
  {
    names: ["Данэ", "Нэрыт", "lазэ", "Нэрыс", "Дэнэф", "Разэ", "Симаз", "Симэ", "Синэмис"],
    avatar: "/lessons/faces/14.png",
  },
  {
    names: ["Сэтэнай", "Нэф", "Нэфын"],
    avatar: "/lessons/faces/10.png",
  },
  {
    names: [
      "Нарт",
      "Енал",
      "Заур",
      "Блан",
      "Пэрыт",
      "Hypбый",
      "Озырмэс",
      "Къазбэч",
      "Батыр",
      "Джэбагъ",
      "Бибэрс",
    ],
    avatar: "/lessons/faces/4.png",
  },
  {
    names: ["Аслъан", "Чан", "Озырмэдж", "Пщымаф", "Тембот"],
    avatar: "/lessons/faces/13.png",
  },
];

export function getCharacterByName(name: string): ICharacter {
  const found = LESSON_CHARACTERS.find((character) => {
    return character.names.includes(name);
  });
  return {
    name: name,
    avatar: found?.avatar || "/lessons/faces/16.png",
  };
}

export const LESSONS_LIST: ILesson[] = [
  {
    lessonIdx: 0,
    title: "The Letters",
    panelIdxList: [
      { title: "0.1 Dialogue 1", component: <Lesson_0_1 /> },
      { title: "1.1 Dialogue 1", component: <Lesson_0_2 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_3 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_4 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_5 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_6 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_7 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_8 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_9 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_10 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_11 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_12 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_13 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_14 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_15 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_16 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_17 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_18 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_19 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_20 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_21 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_22 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_23 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_24 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_25 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_26 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_27 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_28 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_29 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_30 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_31 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_32 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_33 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_34 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_35 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_36 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_37 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_38 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_39 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_40 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_41 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_42 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_43 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_44 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_45 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_46 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_47 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_48 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_49 /> },
      { title: "1.2 Dialogue 1", component: <Lesson_0_50 /> },
    ],
  },
  {
    lessonIdx: 1,
    title: "Welcome",
    panelIdxList: [
      { title: "1.2 Dialogue 1", component: <Lesson_1_1 /> },
      { title: "1.2 Dialogue 2", component: <Lesson_1_2 /> },
      { title: "2.1 Dialogue 1", component: <Lesson_1_3 /> },
      { title: "2.1 Dialogue 2", component: <Lesson_1_4 /> },
      { title: "2.1 Dialogue 3", component: <Lesson_1_5 /> },
      { title: "3.1 Dialogue 1", component: <Lesson_1_6 /> },
      { title: "3.2 Dialogue 1", component: <Lesson_1_6 /> },
      { title: "4.1 Dialogue 1", component: <Lesson_1_7 /> },
      { title: "4.2 Dialogue 1", component: <Lesson_1_8 /> },
      { title: "4.2 Dialogue 2", component: <Lesson_1_9 /> },
      { title: "4.2 Dialogue 1", component: <Lesson_1_10 /> },
      { title: "7.1 Dialogue 1", component: <Lesson_1_11 /> },
      { title: "9.1 Dialogue 1", component: <Lesson_1_12 /> },
      { title: "9.2 Dialogue 1", component: <Lesson_1_13 /> },
      { title: "9.3 Dialogue 1", component: <Lesson_1_14 /> },
      { title: "9.3 Dialogue 2", component: <Lesson_1_15 /> },
      { title: "11.1 Dialogue 1", component: <Lesson_1_16 /> },
      { title: "11.1 Dialogue 2", component: <Lesson_1_17 /> },
      { title: "11.1 Dialogue 3", component: <Lesson_1_18 /> },
    ],
  },
];
